apiVersion: iammanager.keikoproj.io/v1alpha1
kind: Iamrole
metadata:
  name: iamrole-sample
spec:
  # Add fields here
  PolicyDocument:
    Statement:
      -
        Effect: "Allow"
        Action:
          - "ec2:Describe*"
        Resource:
          - "*"
        Sid: "AllowEC2Describe"
